### ISSUE TITLE
Closing Braces

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/swift-style-guide#13]
Method braces and other braces (`guard`, `if` / `else` / `switch` / `while`, etc) braces will always open on the same line, but will close on a new line. 

### Examples

```swift
// Correct
guard condition else {
   return
}

// Correct
if condition { 

} else  {

}

// Wrong
guard condition else { return }

// Wrong
if condition { } else { }
```

### Rationale

`guard` statements are meant to check on a condicion, perform error handling (if needed), and bail out from the current method.

It's common to see a `guard` statement with multiple handling lines. The goal of this proposal is to:

- Improve readability, so that horizontal scrolling is avoided
- Prevent `guard` statements from looking differently, on a case by case scenario

As a reference, i'm quoting [RWC's spacing guideline](https://github.com/raywenderlich/swift-style-guide#spacing).

### Enforcing the rule

Automattic enforcing is yet to be researched.

**Comment by koke** [comment]
> Automattic enforcing is yet to be researched

Not an exact match, but the [conditional_returns_on_newline](https://github.com/realm/SwiftLint/blob/master/Rules.md#closing-brace-spacing) rule should take care of the most common case.

If we accept this, I'd merge it with the [Opening braces](https://github.com/wordpress-mobile/swift-style-guide#opening-braces) rule.

**Comment by frosty** [comment]
My vote would actually be for this modified version of the rule:

Method braces and other braces (guard, if / else / switch / while, etc) braces will always open on the same line, but will close on a new line. The only exception to this rule is `guard` statements that do nothing other than `return` on failure.

```
// Correct
if condition { 

} else  {

}

// Correct
guard condition else { return }

guard condition else {
    // Do something
   return someValue
}

// Wrong
if condition { } else { }
```

**Comment by SergioEstevao** [comment]
@jleandroperez there is a rule in swiftlint for it, the only thing is that it doesn't do autocorrect for it.

Hound-CI uses the swiftlint rules so should be enforceable.

**Comment by koke** [comment]
@frosty I've done the single line return sometimes when there's one short condition:

```swift
guard let client = self else { return }
```

It makes for a more vertically compact code, but on the other hand it makes the return less obvious and could add confusion. In the end, I think we were trying to use this as a sort of `precondition()` that returns instead of stopping execution.

**Comment by bummytime** [comment]
I can get behind what @jleandroperez is asking for here. +1 for consistency.
