### ISSUE TITLE
Colon spacing

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/swift-style-guide#3]
Colons always have no space on the left and one space on the right when specifying a type.
### Examples

``` swift
// Correct
let name: String
struct MyType: MyProtocol {}
func prompt<T: UIViewController where T: Confirmable>(t: T) {}

// Wrong
let name : String
struct MyType : MyProtocol {}
func prompt<T : UIViewController where T : Confirmable>(t: T) {}
```
### Rationale

[Swift Colon Care: High Fiber usage](http://ericasadun.com/2016/03/25/swift-colon-care-high-fiber-usage/) details the rationale and alternatives pretty well.

> This approach is consistent, prioritizes the role of the left item, and is (in my opinion) quite readable.

While the stdlib uses _a space on both sides of the colon when it’s used for declaration or extension_, Apple Developer publications _always write colons with no space on the left (except ternary)_.
### Impact to existing code

There are 795 violations in the WordPress app. SwiftLint can autocorrect all of them.
### Enforcing the rule

SwiftLint includes a `colon` rule that implements this.

**Comment by diegoreymendez** [comment]
@koke - This seems like a reasonable proposal, and there have been no arguments against it since May 10.  Can you create a PR with the additions?
