### ISSUE TITLE
Opening braces on same line

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/swift-style-guide#4]
Opening braces should be preceded by a single space and on the same line as the declaration. The exception to this rule is when enclosed within parentheses: no preceding space is required.
### Examples

``` swift
// Correct
if let myString = myString {
    print(myString)
}

struct Foo {
    let bar: String
}

foo.map({ print($0) })

// Wrong
if let myString = myString
{
    print(myString)
}

struct Foo
{
    let bar: String
}
```
### Rationale

This style is used by Apple in all documentation that I've seen (including The Swift Programming Language), as well as in the Swift stdlib itself. This is also the default for Xcode's autocompletion snippets. 
### Impact to existing code

There are 300 violations in the WordPress app. SwiftLint can autocorrect all of them.
### Enforcing the rule

SwiftLint includes an `opening_brace` rule that implements this.

**Comment by diegoreymendez** [comment]
@frosty - This seems like something we can push into the guide as it is.  Can you create a PR for the changes?
