### ISSUE TITLE
Don't allow optional parameters and then return when they're nil.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/swift-style-guide#5]
Don't allow optional parameters and then return when they're `nil`.
### Examples

``` swift
// Wrong: the return value becomes an optional as well.  Added complexity.
//
func process(image: UIImage?) -> UIImage? {
    if image == nil {
        return nil
    }

    // ...process the image...
}
```

``` swift
// Correct: the return value has a chance to become non-optional.  Reduced complexity.
//
func process(image: UIImage) -> UIImage {
    // ...process the image...
}
```
### Alternative:

As suggested by @koke, if you really need to perform an operation with an optional where `nil` means no-op, you can use `Optional.map`.
### Rationale

A few advantages of this approach:
1. A better separation of unwrapping logic, and actual business logic: in the example above, a method to process an image shouldn't need to worry about whether the caller has actually passed an image or not.
2. Less input optionals means less output optionals: return values are more likely to be non-optional in methods that don't accept unnecessary input optionals.
3. Less unnecessary calls: calls that become no-ops when receiving `nil` parameters are just negative overhead in our code execution.
4. Ease of understanding our code:

``` swift
// When image is not unwrapped...
if let outputImage = processImage(image) {
    // Do something with the outputImage
} else {
    // What failed???
}

// When image is unwrapped...
if let image = image {
    let outputImage = processImage(image)
    // Do something with the outputImage
} else {
    // There's no image to process...
}
```
### Enforcing the rule

Manual peer reviews.

**Comment by koke** [comment]
Your `unwrapAndProcess` is `Optional.map` 😉

**Comment by diegoreymendez** [comment]
We can remove the exception if we find `Optional.map` is a better option.  I'm not particularly fond of the exception case.
