### ISSUE TITLE
Error handling guidelines proposal

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/swift-style-guide#8]
### Description

This proposal tries to provide more precise guidelines we can follow for unifying error handling.

To achieve this, this proposal introduces a distinction between internal and external errors.  There are more details about this distinction in the rationale section below.

Actual proposal:
- Use exceptions for external errors, and handle those exceptions.
- Use `assertion` for internal errors, if we can ignore the error without having to add extra code to recover from it.
  - Fails in DEBUG and silently fails in RELEASE.
- Use `precondition` or `fatalError` for internal errors, if we can't silently fail without adding more code to recover from the error (for example if we need to change the method to return an optional).
  - Fails in DEBUG and RELEASE.

### Examples

```swift
// Exception
func load(fileName: String, fileType: String) throws -> Data {
    guard let url = Bundle.main.url(forResource: fileName, withExtension: fileType) else {
        raise MyExceptions.fileNotFound
    }   
    return Data(contentsOf: url)
}

// IMPORTANT: the following two examples are only valid in a scenario were the
// cast failing would be indicative of an invalid internal state of the app.
// There's no need to do any error handling if the cast failing is expected
// in the normal flow of the app.

// Assertion
func process(someObject: Any) {
    guard let element = someObject as? Element else {
        assertionFailure("This cast should not be failing.")
        return
    }
    process(element)
}

// Precondition & Fatal Error: no way to silently fail without returning an optional
func process(someObject: Any) -> Int {
    guard let element = someObject as? Element else {
        fatalError("This cast should not be failing.")
    }
    return process(element)
}
```

### Rationale

There's a distinction between internal and external errors that we're failing to acknowledge:

- Internal errors exist in the main project's internal logic or in any third party framework the project is using.  They are the sole responsibility of the development team to prevent, and under normal circumstances cannot be reproduced by testers, without modifying the project's internal logic.

- External errors are not caused by the main project's internal logic or its frameworks directly.  They are normally caused by I/O interactions with sources that can be affected by availability (servers), corruption (databases), human error (user input), etc.  Testers should be able to reproduce them without modifying the main project's internal logic.

Due to their nature, internal errors should not have code paths to handle them (since those paths would have to be tested and maintained regularly), whereas external errors should.

### Enforcing the rule

Peer reviews.

**Comment by koke** [comment]
I'd agree with this, but it looks so obviously right to me that I wonder if it's really a style guide thing, or just the right way to do error handling in Swift.

**Comment by diegoreymendez** [comment]
Agreed in principle.  The problem, however, is that I've not been able to find any documentation from Apple's side to back this statement up, which opens up the door for unnecessary discussion in PRs.

One example of possible confusion can be found in the error handling provided in the "unrecoverable example" in [this proposal](https://github.com/wordpress-mobile/swift-style-guide/issues/7):

```swift
func processedItems() throws -> Int {
    guard items = theseThings as? [Item] else {
        throw ThingItemsError.ProcessingError
    }
    return process(items)
}
```

There are also examples in our WPiOS codebase showing possible disagreement: [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Networking/BlogServiceRemoteREST.m#L121),  [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Networking/BlogServiceRemoteREST.m#L271).

Granted, the examples are Objective-C code.  But the error handling principles should have been the same there too, meaning there's at least some space for confusion.
